pool_info:
  default_res: Chia reference pool
  name: Dishwasha Pool
  logo_url: https://www.chia.net/img/chia_logo.svg
  description: (example) The Reference Pool allows you to pool with low fees, paying out daily using Chia.
welcome_message: "Welcome to the reference pool!"
pool_fee: 0.00
block_claim_fee: 0
pool_url: https://pool.diytestequipment.com:8443
min_difficulty: 1
default_difficulty: 1
default_target_address: xch127ndn8lwratckw9jas8z6gl2qkgceky7w9q0sqq0fykk367srsvsc3hurv
pool_fee_address: xch127ndn8lwratckw9jas8z6gl2qkgceky7w9q0sqq0fykk367srsvsc3hurv
wallet_fingerprint: 62561831
authentication_token_timeout: 5
wallet_id: 1
node_rpc_port: 8555
wallet_rpc_port: 9256
partial_time_limit: 25
partial_confirmation_delay: 300
scan_start_height: 1000
collect_pool_rewards_interval: 600
confirmation_security_threshold: 32
payment_interval: 600
max_additions_per_transaction: 400
number_of_partials_target: 300
time_target: 86400
relative_lock_height: 32
logging:
  log_path: /var/log/chia
  log_filename: pool-server.log
  log_level: INFO
  log_maxfilesrotation: 7
  log_stdout: false
server:
  server_host: 0.0.0.0
  server_port: 8443
  server_use_ssl: true
  server_ssl_crt: /home/ewaldo/.chia/mainnet/config/ssl/pool/pool.crt
  server_ssl_key: /home/ewaldo/.chia/mainnet/config/ssl/pool/pool.key
